# Clocks setup (chronyd)
- name: Add local NTP-server to chrony conf
  command: echo "Server {{ ntp_server }}" >> /etc/chrony.conf

- name: Restart chronyd
  systemd:
    name: chronyd
    state: restarted
    enabled: yes
